/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import javax.swing.*;

public class ServerGUI extends JFrame {

    public ServerGUI() {
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        TabPane = new javax.swing.JTabbedPane();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        main_table = new javax.swing.JTable();
        jToolBar1 = new javax.swing.JToolBar();
        RemoteDesktopButton = new javax.swing.JButton();
        ShutdownButton = new javax.swing.JButton();
        RestartButton = new javax.swing.JButton();
        ActivityLogButton = new javax.swing.JButton();
        BlacklistBt = new javax.swing.JButton();
        AppsButton = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        btRegister = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        ipAddress = new javax.swing.JTextField();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        exit = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("T-GROUP SERVER");
        setResizable(false);

        jScrollPane3.setPreferredSize(new java.awt.Dimension(700, 375));

        tbModel = new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Computer Name", "IP Address", "Status", "Start Time"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        };
        main_table.setModel(tbModel);
        main_table.setPreferredSize(new java.awt.Dimension(600, 300));
        jScrollPane3.setViewportView(main_table);

        jToolBar1.setRollover(true);
        jToolBar1.setEnabled(false);

        RemoteDesktopButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/model/icon/monitor-desktop-icon.png"))); // NOI18N
        RemoteDesktopButton.setText("Remote Desktop");
        RemoteDesktopButton.setFocusable(false);
        RemoteDesktopButton.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        RemoteDesktopButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(RemoteDesktopButton);

        ShutdownButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/model/icon/shutdown-icon.png"))); // NOI18N
        ShutdownButton.setText("Shutdown");
        ShutdownButton.setFocusable(false);
        ShutdownButton.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        ShutdownButton.setInheritsPopupMenu(true);
        ShutdownButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(ShutdownButton);

        RestartButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/model/icon/NX1-Restart-icon.png"))); // NOI18N
        RestartButton.setText("Restart");
        RestartButton.setFocusable(false);
        RestartButton.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        RestartButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(RestartButton);

        ActivityLogButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/model/icon/Browser-icon.png"))); // NOI18N
        ActivityLogButton.setText("Activity Log ");
        ActivityLogButton.setFocusable(false);
        ActivityLogButton.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        ActivityLogButton.setInheritsPopupMenu(true);
        ActivityLogButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(ActivityLogButton);

        BlacklistBt.setIcon(new javax.swing.ImageIcon(getClass().getResource("/model/icon/log_in.png"))); // NOI18N
        BlacklistBt.setText("Blacklist");
        BlacklistBt.setFocusable(false);
        BlacklistBt.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        BlacklistBt.setMaximumSize(new java.awt.Dimension(85, 23));
        BlacklistBt.setMinimumSize(new java.awt.Dimension(85, 23));
        BlacklistBt.setPreferredSize(new java.awt.Dimension(85, 23));
        BlacklistBt.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(BlacklistBt);

        AppsButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/model/icon/Apps-system-software-update-icon.png"))); // NOI18N
        AppsButton.setText("Application");
        AppsButton.setFocusable(false);
        AppsButton.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        AppsButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(AppsButton);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 728, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 281, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        TabPane.addTab("Features", jPanel3);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Registration"));

        btRegister.setText("Resgister");

        jLabel1.setText("IP Address");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(35, 35, 35)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ipAddress)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(67, 67, 67)
                        .addComponent(btRegister)
                        .addGap(0, 156, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(78, 78, 78)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(ipAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addComponent(btRegister)
                .addGap(55, 55, 55))
        );

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(110, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(199, 199, 199))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(45, Short.MAX_VALUE))
        );

        TabPane.addTab("Registration", jPanel4);

        jMenu1.setText("File");
        jMenu1.setFocusable(false);

        exit.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F4, java.awt.event.InputEvent.ALT_DOWN_MASK));
        exit.setText("Exit");
        jMenu1.add(exit);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(TabPane, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(TabPane, javax.swing.GroupLayout.PREFERRED_SIZE, 354, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        TabPane.getAccessibleContext().setAccessibleName("Function");
        TabPane.getAccessibleContext().setAccessibleDescription("Function");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ActivityLogButton;
    public javax.swing.JButton AppsButton;
    public javax.swing.JButton BlacklistBt;
    public javax.swing.JButton RemoteDesktopButton;
    public javax.swing.JButton RestartButton;
    public javax.swing.JButton ShutdownButton;
    private javax.swing.JTabbedPane TabPane;
    public javax.swing.JButton btRegister;
    private javax.swing.JMenuItem exit;
    public javax.swing.JTextField ipAddress;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JToolBar jToolBar1;
    public javax.swing.JTable main_table;
    public javax.swing.table.DefaultTableModel tbModel;
    // End of variables declaration//GEN-END:variables
}
